name: Deploy Mahdara to GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Mahdara
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout mahdara repo
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Mahdara project
        run: npm run build
        
      - name: Upload production build files
        uses: actions/upload-artifact@v4
        with:
          name: mahdara-build
          path: ./dist

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: mahdara-build
          path: ./dist
          
      - name: Deploy Mahdara to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'